#priority 9400

import crafttweaker.item.IItemStack;
import crafttweaker.liquid.ILiquidStack;

static items as IItemStack [][string]  = {
    "Stone age stuff" : [
        <advancedrocketry:alienleaves>,
        <advancedrocketry:alienwood>,
        <advancedrocketry:basalt>,
        <advancedrocketry:geode>,
        <advancedrocketry:misc:1>,
        <advancedrocketry:planks>,
        <basketcase:container_basket_large>,
        <basketcase:container_basket_medium>,
        <basketcase:container_basket_small>,
        <basketcase:item_bark_acacia>,
        <basketcase:item_bark_birch>,
        <basketcase:item_bark_dark_oak>,
        <basketcase:item_bark_jungle>,
        <basketcase:item_bark_oak>,
        <basketcase:item_bark_spruce>,
        <basketcase:item_bark_strips>,
        <basketcase:item_cordage>,
        <basketcase:item_plant_fiber>,
        <basketcase:item_twig>,
        <basketcase:item_wicker_large>,
        <basketcase:item_wicker_medium>,
        <basketcase:item_wicker_small>,
        <basketcase:log_stripped_acacia>,
        <basketcase:log_stripped_birch>,
        <basketcase:log_stripped_dark_oak>,
        <basketcase:log_stripped_jungle>,
        <basketcase:log_stripped_oak>,
        <basketcase:log_stripped_spruce>,
        <bountiful:bounty>,
        <bountiful:bountyboarditem>,
        <comforts:hammock>,
        <comforts:hammock:1>,
        <comforts:hammock:2>,
        <comforts:hammock:3>,
        <comforts:hammock:4>,
        <comforts:hammock:5>,
        <comforts:hammock:6>,
        <comforts:hammock:7>,
        <comforts:hammock:8>,
        <comforts:hammock:9>,
        <comforts:hammock:10>,
        <comforts:hammock:11>,
        <comforts:hammock:12>,
        <comforts:hammock:13>,
        <comforts:hammock:14>,
        <comforts:hammock:15>,
        <comforts:rope>,
        <comforts:sleeping_bag>,
        <comforts:sleeping_bag:1>,
        <comforts:sleeping_bag:2>,
        <comforts:sleeping_bag:3>,
        <comforts:sleeping_bag:4>,
        <comforts:sleeping_bag:5>,
        <comforts:sleeping_bag:6>,
        <comforts:sleeping_bag:7>,
        <comforts:sleeping_bag:8>,
        <comforts:sleeping_bag:9>,
        <comforts:sleeping_bag:10>,
        <comforts:sleeping_bag:11>,
        <comforts:sleeping_bag:12>,
        <comforts:sleeping_bag:13>,
        <comforts:sleeping_bag:14>,
        <comforts:sleeping_bag:15>,
        <geolosys:cluster>,
        <geolosys:cluster:1>,
        <geolosys:cluster:2>,
        <geolosys:cluster:3>,
        <geolosys:cluster:4>,
        <geolosys:cluster:5>,
        <geolosys:cluster:6>,
        <geolosys:cluster:7>,
        <geolosys:cluster:8>,
        <geolosys:cluster:9>,
        <geolosys:cluster:10>,
        <geolosys:cluster:11>,
        <geolosys:cluster:12>,
        <geolosys:coal>,
        <geolosys:coal:1>,
        <geolosys:coal:2>,
        <geolosys:coal:3>,
        <geolosys:coal_coke>,
        <geolosys:coal_coke:1>,
        <geolosys:field_manual>,
        <geolosys:ingot>,
        <geolosys:ingot:1>,
        <geolosys:ingot:2>,
        <geolosys:ingot:3>,
        <geolosys:ingot:4>,
        <geolosys:ingot:5>,
        <geolosys:ingot:6>,
        <geolosys:ingot:7>,
        <geolosys:ore>,
        <geolosys:ore:1>,
        <geolosys:ore:2>,
        <geolosys:ore:3>,
        <geolosys:ore:4>,
        <geolosys:ore:5>,
        <geolosys:ore:6>,
        <geolosys:ore:7>,
        <geolosys:ore:8>,
        <geolosys:ore:9>,
        <geolosys:ore:10>,
        <geolosys:ore_sample>,
        <geolosys:ore_sample:1>,
        <geolosys:ore_sample:2>,
        <geolosys:ore_sample:3>,
        <geolosys:ore_sample:4>,
        <geolosys:ore_sample:5>,
        <geolosys:ore_sample:6>,
        <geolosys:ore_sample:7>,
        <geolosys:ore_sample:8>,
        <geolosys:ore_sample:9>,
        <geolosys:ore_sample:10>,
        <geolosys:ore_sample_vanilla>,
        <geolosys:ore_sample_vanilla:1>,
        <geolosys:ore_sample_vanilla:2>,
        <geolosys:ore_sample_vanilla:3>,
        <geolosys:ore_sample_vanilla:4>,
        <geolosys:ore_sample_vanilla:5>,
        <geolosys:ore_sample_vanilla:6>,
        <geolosys:ore_vanilla>,
        <geolosys:ore_vanilla:1>,
        <geolosys:ore_vanilla:2>,
        <geolosys:ore_vanilla:3>,
        <geolosys:ore_vanilla:4>,
        <geolosys:ore_vanilla:5>,
        <geolosys:ore_vanilla:6>,
        <geolosys:pro_pick>,
        <harvestcraft:aridgarden>,
        <immcraft:bookshelf>,
        <immcraft:bookstand>,
        <immcraft:bundle>,
        <immcraft:chest>,
        <immcraft:chisel>,
        <immcraft:cupboard>,
        <immcraft:dummybook>,
        <immcraft:dummybook:1>,
        <immcraft:dummybook:2>,
        <immcraft:dummybook:3>,
        <immcraft:dummybook:4>,
        <immcraft:dummybook:5>,
        <immcraft:dummybook:6>,
        <immcraft:dummybook:7>,
        <immcraft:furnace>,
        <immcraft:in_world_placer>,
        <immcraft:in_world_vertical_placer>,
        <immcraft:manual>,
        <immcraft:rock>,
        <immcraft:saw>,
        <immcraft:shelf>,
        <immcraft:sticks>,
        <immcraft:workbench>,
        <immcraft:workbench_sec>,
        <minecraft:apple>,
        <minecraft:beef>,
        <minecraft:beetroot>,
        <minecraft:bone>,
        <minecraft:bone_block>,
        <minecraft:bowl>,
        <minecraft:brown_mushroom>,
        <minecraft:brown_mushroom_block>,
        <minecraft:cactus>,
        <minecraft:clay>,
        <minecraft:clay_ball>,
        <minecraft:clownfish>,
        <minecraft:coal>,
        <minecraft:coal:1>,
        <minecraft:coal_block>,
        <minecraft:coal_ore>,
        <minecraft:cobblestone>,
        <minecraft:cobblestone_wall>,
        <minecraft:cobblestone_wall:1>,
        <minecraft:cod>,
        <minecraft:concrete>,
        <minecraft:concrete:1>,
        <minecraft:concrete:2>,
        <minecraft:concrete:3>,
        <minecraft:concrete:4>,
        <minecraft:concrete:5>,
        <minecraft:concrete:6>,
        <minecraft:concrete:7>,
        <minecraft:concrete:8>,
        <minecraft:concrete:9>,
        <minecraft:concrete:10>,
        <minecraft:concrete:11>,
        <minecraft:concrete:12>,
        <minecraft:concrete:13>,
        <minecraft:concrete:14>,
        <minecraft:concrete:15>,
        <minecraft:deadbush>,
        <minecraft:dirt>,
        <minecraft:dirt:1>,
        <minecraft:dirt:2>,
        <minecraft:double_plant>,
        <minecraft:double_plant:1>,
        <minecraft:double_plant:2>,
        <minecraft:double_plant:3>,
        <minecraft:double_plant:4>,
        <minecraft:double_plant:5>,
        <minecraft:dye>,
        <minecraft:dye:1>,
        <minecraft:dye:2>,
        <minecraft:dye:3>,
        <minecraft:dye:4>,
        <minecraft:dye:5>,
        <minecraft:dye:6>,
        <minecraft:dye:7>,
        <minecraft:dye:8>,
        <minecraft:dye:9>,
        <minecraft:dye:10>,
        <minecraft:dye:11>,
        <minecraft:dye:12>,
        <minecraft:dye:13>,
        <minecraft:dye:14>,
        <minecraft:dye:15>,
        <minecraft:feather>,
        <minecraft:fishing_rod>,
        <minecraft:flint>,
        <minecraft:flower_pot>,
        <minecraft:grass>,
        <minecraft:grass_path>,
        <minecraft:gravel>,
        <minecraft:hardened_clay>,
        <minecraft:hay_block>,
        <minecraft:ice>,
        <minecraft:lapis_block>,
        <minecraft:lapis_ore>,
        <minecraft:lead>,
        <minecraft:leather>,
        <minecraft:leather_boots>,
        <minecraft:leather_chestplate>,
        <minecraft:leather_helmet>,
        <minecraft:leather_leggings>,
        <minecraft:leaves>,
        <minecraft:leaves:1>,
        <minecraft:leaves:2>,
        <minecraft:leaves:3>,
        <minecraft:leaves2>,
        <minecraft:leaves2:1>,
        <minecraft:log>,
        <minecraft:log:1>,
        <minecraft:log:2>,
        <minecraft:log:3>,
        <minecraft:log2>,
        <minecraft:log2:1>,
        <minecraft:mossy_cobblestone>,
        <minecraft:mycelium>,
        <minecraft:packed_ice>,
        <minecraft:planks>,
        <minecraft:planks:1>,
        <minecraft:planks:2>,
        <minecraft:planks:3>,
        <minecraft:planks:4>,
        <minecraft:planks:5>,
        <minecraft:rabbit_hide>,
        <minecraft:red_flower>,
        <minecraft:red_flower:1>,
        <minecraft:red_flower:2>,
        <minecraft:red_flower:3>,
        <minecraft:red_flower:4>,
        <minecraft:red_flower:5>,
        <minecraft:red_flower:6>,
        <minecraft:red_flower:7>,
        <minecraft:red_flower:8>,
        <minecraft:red_sandstone>,
        <minecraft:red_sandstone:1>,
        <minecraft:red_sandstone:2>,
        <minecraft:red_sandstone_stairs>,
        <minecraft:sand>,
        <minecraft:sand:1>,
        <minecraft:sandstone>,
        <minecraft:sandstone:1>,
        <minecraft:sandstone:2>,
        <minecraft:skull>,
        <minecraft:skull:1>,
        <minecraft:skull:2>,
        <minecraft:skull:3>,
        <minecraft:skull:4>,
        <minecraft:skull:5>,
        <minecraft:slime>,
        <minecraft:slime_ball>,
        <minecraft:snow>,
        <minecraft:snow_layer>,
        <minecraft:snowball>,
        <minecraft:sponge>,
        <minecraft:sponge:1>,
        <minecraft:stained_hardened_clay>,
        <minecraft:stained_hardened_clay:1>,
        <minecraft:stained_hardened_clay:2>,
        <minecraft:stained_hardened_clay:3>,
        <minecraft:stained_hardened_clay:4>,
        <minecraft:stained_hardened_clay:5>,
        <minecraft:stained_hardened_clay:6>,
        <minecraft:stained_hardened_clay:7>,
        <minecraft:stained_hardened_clay:8>,
        <minecraft:stained_hardened_clay:9>,
        <minecraft:stained_hardened_clay:10>,
        <minecraft:stained_hardened_clay:11>,
        <minecraft:stained_hardened_clay:12>,
        <minecraft:stained_hardened_clay:13>,
        <minecraft:stained_hardened_clay:14>,
        <minecraft:stained_hardened_clay:15>,
        <minecraft:stick>,
        <minecraft:stone>,
        <minecraft:stone:1>,
        <minecraft:stone:2>,
        <minecraft:stone:3>,
        <minecraft:stone:4>,
        <minecraft:stone:5>,
        <minecraft:stone:6>,
        <minecraft:stone_axe>,
        <minecraft:stone_hoe>,
        <minecraft:stone_pickaxe>,
        <minecraft:stone_shovel>,
        <minecraft:stone_slab>,
        <minecraft:stone_slab:1>,
        <minecraft:stone_slab:3>,
        <minecraft:stone_slab:4>,
        <minecraft:stone_slab:5>,
        <minecraft:stone_slab:6>,
        <minecraft:stone_slab:7>,
        <minecraft:stone_slab2>,
        <minecraft:stone_sword>,
        <minecraft:string>,
        <minecraft:tallgrass:1>,
        <minecraft:tallgrass:2>,
        <minecraft:torch>,
        <minecraft:totem_of_undying>,
        <minecraft:vine>,
        <minecraft:waterlily>,
        <minecraft:web>,
        <minecraft:wooden_axe>,
        <minecraft:wooden_hoe>,
        <minecraft:wooden_pickaxe>,
        <minecraft:wooden_shovel>,
        <minecraft:wooden_slab>,
        <minecraft:wooden_slab:1>,
        <minecraft:wooden_slab:2>,
        <minecraft:wooden_slab:3>,
        <minecraft:wooden_slab:4>,
        <minecraft:wooden_slab:5>,
        <minecraft:wooden_sword>,
        <minecraft:wool>,
        <minecraft:wool:1>,
        <minecraft:wool:2>,
        <minecraft:wool:3>,
        <minecraft:wool:4>,
        <minecraft:wool:5>,
        <minecraft:wool:6>,
        <minecraft:wool:7>,
        <minecraft:wool:8>,
        <minecraft:wool:9>,
        <minecraft:wool:10>,
        <minecraft:wool:11>,
        <minecraft:wool:12>,
        <minecraft:wool:13>,
        <minecraft:wool:14>,
        <minecraft:wool:15>,
        <minecraft:yellow_flower>,
        <primal:aconite>,
        <primal:aconite_petal>,
        <primal:aconite_root>,
        <primal:aconite_sprig>,
        <primal:adamant_dust>,
        <primal:adamant_ingot>,
        <primal:adamant_nugget>,
        <primal:adamant_plate>,
        <primal:adobe_brick>,
        <primal:adobe_brick_dry>,
        <primal:adobe_brick_wet>,
        <primal:adobe_clump>,
        <primal:aluminum_dust>,
        <primal:aluminum_ingot>,
        <primal:aluminum_nugget>,
        <primal:aluminum_plate>,
        <primal:ancient_ice>,
        <primal:ancient_ice_chunk>,
        <primal:animal_fat>,
        <primal:animal_fat_nether>,
        <primal:animal_fur>,
        <primal:armor_obsidian_body>,
        <primal:armor_obsidian_feet>,
        <primal:armor_obsidian_goggles>,
        <primal:armor_obsidian_head>,
        <primal:armor_obsidian_legs>,
        <primal:armor_ovis_body>,
        <primal:armor_ovis_feet>,
        <primal:armor_ovis_head>,
        <primal:armor_ovis_legs>,
        <primal:armor_wolf_body>,
        <primal:armor_wolf_feet>,
        <primal:armor_wolf_head>,
        <primal:armor_wolf_legs>,
        <primal:arrow_bitumen>,
        <primal:arrow_ironwood>,
        <primal:arrow_paraffin>,
        <primal:arrow_quartz>,
        <primal:arrow_torch_nether>,
        <primal:arrow_torch_redstone>,
        <primal:arrow_torch_wood>,
        <primal:arrow_water>,
        <primal:ash_bone>,
        <primal:ash_common>,
        <primal:ash_ironwood>,
        <primal:ash_wolf>,
        <primal:ash_yew>,
        <primal:bark_acacia>,
        <primal:bark_bigoak>,
        <primal:bark_birch>,
        <primal:bark_corypha>,
        <primal:bark_ironwood>,
        <primal:bark_jungle>,
        <primal:bark_oak>,
        <primal:bark_spruce>,
        <primal:bark_yew>,
        <primal:barrel>,
        <primal:barrel:1>,
        <primal:barrel:2>,
        <primal:barrel:3>,
        <primal:barrel:4>,
        <primal:barrel:5>,
        <primal:barrel:6>,
        <primal:barrel:7>,
        <primal:barrel:8>,
        <primal:barrel:9>,
        <primal:barrel_acacia_lid>,
        <primal:barrel_birch_lid>,
        <primal:barrel_corypha_lid>,
        <primal:barrel_dark_oak_lid>,
        <primal:barrel_ironwood_lid>,
        <primal:barrel_jungle_lid>,
        <primal:barrel_lacquer_lid>,
        <primal:barrel_oak_lid>,
        <primal:barrel_spruce_lid>,
        <primal:barrel_trap>,
        <primal:barrel_yew_lid>,
        <primal:bat_meat_cooked>,
        <primal:bat_meat_cured>,
        <primal:bat_meat_dried>,
        <primal:bat_meat_raw>,
        <primal:bat_meat_rotten>,
        <primal:bat_meat_salted>,
        <primal:bear_meat_cooked>,
        <primal:bear_meat_dried>,
        <primal:bear_meat_raw>,
        <primal:bear_meat_rotten>,
        <primal:bear_meat_salted>,
        <primal:bitumen>,
        <primal:bitumen_boiling>,
        <primal:bitumin_clump>,
        <primal:blue_stone>,
        <primal:blue_stone:1>,
        <primal:blue_stone:2>,
        <primal:blue_stone:3>,
        <primal:blue_stone:4>,
        <primal:blue_stone:5>,
        <primal:blue_stone:6>,
        <primal:blue_stone:7>,
        <primal:boat_corypha>,
        <primal:boat_ironwood>,
        <primal:boat_lacquer>,
        <primal:boat_yew>,
        <primal:bone_hatchet>,
        <primal:bone_hoe>,
        <primal:bone_knapp>,
        <primal:bone_pickaxe>,
        <primal:bone_point>,
        <primal:bone_saw>,
        <primal:bone_shears>,
        <primal:bone_shovel>,
        <primal:bottle_bitumen>,
        <primal:bottle_paraffin>,
        <primal:brass_dust>,
        <primal:brass_ingot>,
        <primal:brass_nugget>,
        <primal:brass_plate>,
        <primal:brick_mold>.withTag({type: "oak"}),
        <primal:brick_mold:1>.withTag({type: "spruce"}),
        <primal:brick_mold:2>.withTag({type: "birch"}),
        <primal:brick_mold:3>.withTag({type: "jungle"}),
        <primal:brick_mold:4>.withTag({type: "acacia"}),
        <primal:brick_mold:5>.withTag({type: "dark_oak"}),
        <primal:brick_mold:6>.withTag({type: "ironwood"}),
        <primal:brick_mold:7>.withTag({type: "yew"}),
        <primal:brick_mold:8>.withTag({type: "lacquer"}),
        <primal:brick_mold:9>.withTag({type: "corypha"}),
        <primal:brickform>,
        <primal:brine_netjry>,
        <primal:bronze_dust>,
        <primal:bronze_ingot>,
        <primal:bronze_nugget>,
        <primal:bronze_plate>,
        <primal:bucket_cinis>.withTag({Fluid: {}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "water", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "lava", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "iron", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "gold", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "pigiron", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "cobalt", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "ardite", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "manyullyn", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "knightslime", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "alubrass", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "brass", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "copper", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "tin", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "bronze", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "zinc", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "lead", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "nickel", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "silver", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "electrum", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "steel", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "aluminum", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "glowstone", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "redstone", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "ender", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "electrical_steel", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "energetic_alloy", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "vibrant_alloy", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "redstone_alloy", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "conductive_iron", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "pulsating_iron", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "dark_steel", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "soularium", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "end_steel", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "construction_alloy", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "crude_steel", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "crystalline_alloy", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "melodic_alloy", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "stellar_alloy", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "crystalline_pink_slime", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "energetic_silver", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "vivid_alloy", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "creosote", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "plantoil", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "ethanol", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "biodiesel", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "concrete", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "potion", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "uranium", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "constantan", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "oil", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "diesel", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "lubricant", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "gasoline", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "napalm", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "dist_water", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "steam", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "fluid_molten_aer", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "fluid_molten_ignis", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "fluid_molten_aqua", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "fluid_molten_terra", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "fluid_molten_ordo", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "fluid_molten_perditio", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "nutrient_distillation", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "ender_distillation", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "vapor_of_levity", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "hootch", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "rocket_fuel", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "fire_water", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "xpjuice", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "liquid_sunshine", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "cloud_seed", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "cloud_seed_concentrated", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "liquid_death", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "purifying_fluid", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "stone", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "obsidian", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "clay", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "dirt", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "emerald", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "glass", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "blood", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "blueslime", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "purpleslime", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "yellorium", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "cyanite", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "tannin", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "urushi", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "brine_netjry", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "waste", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "bitumen", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "bitumen_boiling", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "paraffin", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "magma_basaltic", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "ovis_atre_milk", Amount: 1000}}),
        <primal:bucket_cinis>.withTag({Fluid: {FluidName: "smoke", Amount: 1000}}),
        <primal:bucket_cinis_milk>,
        <primal:bucket_cinis_soft>,
        <primal:bucket_clay>.withTag({Fluid: {}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "water", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "lava", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "iron", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "gold", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "pigiron", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "cobalt", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "ardite", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "manyullyn", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "knightslime", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "alubrass", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "brass", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "copper", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "tin", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "bronze", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "zinc", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "lead", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "nickel", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "silver", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "electrum", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "steel", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "aluminum", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "glowstone", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "redstone", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "ender", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "electrical_steel", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "energetic_alloy", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "vibrant_alloy", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "redstone_alloy", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "conductive_iron", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "pulsating_iron", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "dark_steel", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "soularium", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "end_steel", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "construction_alloy", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "crude_steel", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "crystalline_alloy", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "melodic_alloy", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "stellar_alloy", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "crystalline_pink_slime", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "energetic_silver", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "vivid_alloy", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "creosote", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "plantoil", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "ethanol", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "biodiesel", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "concrete", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "potion", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "uranium", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "constantan", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "oil", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "diesel", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "lubricant", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "gasoline", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "napalm", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "dist_water", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "steam", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "fluid_molten_aer", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "fluid_molten_ignis", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "fluid_molten_aqua", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "fluid_molten_terra", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "fluid_molten_ordo", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "fluid_molten_perditio", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "nutrient_distillation", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "ender_distillation", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "vapor_of_levity", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "hootch", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "rocket_fuel", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "fire_water", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "xpjuice", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "liquid_sunshine", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "cloud_seed", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "cloud_seed_concentrated", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "liquid_death", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "purifying_fluid", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "stone", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "obsidian", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "clay", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "dirt", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "emerald", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "glass", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "blood", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "blueslime", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "purpleslime", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "yellorium", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "cyanite", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "tannin", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "urushi", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "brine_netjry", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "waste", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "bitumen", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "bitumen_boiling", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "paraffin", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "magma_basaltic", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "ovis_atre_milk", Amount: 1000}}),
        <primal:bucket_clay>.withTag({Fluid: {FluidName: "smoke", Amount: 1000}}),
        <primal:bucket_clay_milk>,
        <primal:bucket_clay_soft>,
        <primal:bucket_terra>.withTag({Fluid: {}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "water", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "lava", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "iron", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "gold", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "pigiron", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "cobalt", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "ardite", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "manyullyn", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "knightslime", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "alubrass", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "brass", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "copper", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "tin", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "bronze", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "zinc", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "lead", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "nickel", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "silver", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "electrum", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "steel", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "aluminum", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "glowstone", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "redstone", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "ender", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "electrical_steel", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "energetic_alloy", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "vibrant_alloy", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "redstone_alloy", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "conductive_iron", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "pulsating_iron", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "dark_steel", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "soularium", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "end_steel", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "construction_alloy", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "crude_steel", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "crystalline_alloy", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "melodic_alloy", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "stellar_alloy", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "crystalline_pink_slime", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "energetic_silver", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "vivid_alloy", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "creosote", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "plantoil", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "ethanol", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "biodiesel", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "concrete", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "potion", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "uranium", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "constantan", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "oil", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "diesel", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "lubricant", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "gasoline", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "napalm", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "dist_water", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "steam", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "fluid_molten_aer", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "fluid_molten_ignis", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "fluid_molten_aqua", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "fluid_molten_terra", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "fluid_molten_ordo", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "fluid_molten_perditio", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "nutrient_distillation", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "ender_distillation", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "vapor_of_levity", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "hootch", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "rocket_fuel", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "fire_water", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "xpjuice", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "liquid_sunshine", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "cloud_seed", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "cloud_seed_concentrated", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "liquid_death", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "purifying_fluid", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "stone", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "obsidian", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "clay", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "dirt", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "emerald", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "glass", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "blood", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "blueslime", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "purpleslime", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "yellorium", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "cyanite", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "tannin", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "urushi", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "brine_netjry", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "waste", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "bitumen", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "bitumen_boiling", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "paraffin", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "magma_basaltic", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "ovis_atre_milk", Amount: 1000}}),
        <primal:bucket_terra>.withTag({Fluid: {FluidName: "smoke", Amount: 1000}}),
        <primal:bucket_terra_milk>,
        <primal:bucket_terra_soft>,
        <primal:calcified_paraffin>,
        <primal:carbon_plate>,
        <primal:carbonate_slack>,
        <primal:carbonate_stone>,
        <primal:carbonate_stone:1>,
        <primal:carbonate_stone:2>,
        <primal:carbonate_stone:3>,
        <primal:carbonate_stone:4>,
        <primal:carbonate_stone:5>,
        <primal:carbonate_stone:6>,
        <primal:carbonate_stone:7>,
        <primal:carpet_cineris>,
        <primal:carpet_inanis>,
        <primal:cauldron>,
        <primal:cauldron_ladle_bone>,
        <primal:cauldron_ladle_corypha>,
        <primal:cauldron_ladle_ironwood>,
        <primal:cauldron_ladle_lacquer>,
        <primal:cauldron_ladle_yew>,
        <primal:cauldron_lid>,
        <primal:charcoal_fair>,
        <primal:charcoal_good>,
        <primal:charcoal_high>,
        <primal:charcoal_mote>,
        <primal:charcoal_pure>,
        <primal:charcoal_stack>,
        <primal:charcoal_stack:1>,
        <primal:charcoal_stack:2>,
        <primal:charcoal_stack:3>,
        <primal:charcoal_stack:4>,
        <primal:cheese_red>,
        <primal:cheese_white>,
        <primal:chum>,
        <primal:cineris_bloom>,
        <primal:cineris_grass>,
        <primal:cinis_block>,
        <primal:cinis_brick_dry>,
        <primal:cinis_brick_wet>,
        <primal:cinis_clump>,
        <primal:ciniscotta_block>,
        <primal:ciniscotta_block:1>,
        <primal:ciniscotta_block:2>,
        <primal:ciniscotta_block:3>,
        <primal:ciniscotta_block:4>,
        <primal:ciniscotta_block:5>,
        <primal:ciniscotta_block:6>,
        <primal:ciniscotta_block:7>,
        <primal:common_stone>,
        <primal:common_stone:1>,
        <primal:common_stone:2>,
        <primal:common_stone:3>,
        <primal:common_stone:4>,
        <primal:common_stone:5>,
        <primal:common_stone:6>,
        <primal:common_stone:7>,
        <primal:copper_dust>,
        <primal:copper_ingot>,
        <primal:copper_nugget>,
        <primal:copper_plate>,
        <primal:copper_saw>,
        <primal:copper_strand>,
        <primal:corn_bread>,
        <primal:corn_cob>,
        <primal:corn_cob_cooked>,
        <primal:corn_ground>,
        <primal:corn_seeds>,
        <primal:corn_stalk>,
        <primal:corn_stalk_dry>,
        <primal:corn_stalk_wet>,
        <primal:corypha_bow>,
        <primal:corypha_pin>,
        <primal:corypha_seed>,
        <primal:corypha_stalk>,
        <primal:corypha_stalk:1>,
        <primal:corypha_stick>,
        <primal:crude_iron_dust>,
        <primal:crude_iron_ingot>,
        <primal:crude_iron_nugget>,
        <primal:crude_iron_plate>,
        <primal:daucus_murn>,
        <primal:daucus_murn_fronds>,
        <primal:daucus_murn_fronds_withered>,
        <primal:daucus_murn_root>,
        <primal:daucus_murn_root_cooked>,
        <primal:daucus_murn_seeds>,
        <primal:desiccated_stone>,
        <primal:desiccated_stone:1>,
        <primal:desiccated_stone:2>,
        <primal:desiccated_stone:3>,
        <primal:desiccated_stone:4>,
        <primal:desiccated_stone:5>,
        <primal:desiccated_stone:6>,
        <primal:desiccated_stone:7>,
        <primal:devils_tongue>,
        <primal:devils_tongue_sepals>,
        <primal:devils_tongue_tendril>,
        <primal:diamond_axe>,
        <primal:diamond_hatchet>,
        <primal:diamond_hoe>,
        <primal:diamond_knapp>,
        <primal:diamond_pickaxe>,
        <primal:diamond_plate>,
        <primal:diamond_point>,
        <primal:diamond_saw>,
        <primal:diamond_shovel>,
        <primal:diamond_workblade>,
        <primal:dirt_stick>,
        <primal:door_corypha>,
        <primal:door_ironwood>,
        <primal:door_lacquer>,
        <primal:door_yew>,
        <primal:drain_carbonate_flag>,
        <primal:drain_ciniscotta>,
        <primal:drain_ferro_flag>,
        <primal:drain_mud>,
        <primal:drain_nether_earth>,
        <primal:drain_netherstone>,
        <primal:drain_schist_green>,
        <primal:drain_scoria>,
        <primal:drain_stonebrick>,
        <primal:drain_thatch>,
        <primal:dry_grass>,
        <primal:dry_grass_root>,
        <primal:dry_grass_seed>,
        <primal:drying_rack>.withTag({type: "oak"}),
        <primal:drying_rack:1>.withTag({type: "spruce"}),
        <primal:drying_rack:2>.withTag({type: "birch"}),
        <primal:drying_rack:3>.withTag({type: "jungle"}),
        <primal:drying_rack:4>.withTag({type: "acacia"}),
        <primal:drying_rack:5>.withTag({type: "dark_oak"}),
        <primal:drying_rack:6>.withTag({type: "ironwood"}),
        <primal:drying_rack:7>.withTag({type: "yew"}),
        <primal:drying_rack:8>.withTag({type: "lacquer"}),
        <primal:drying_rack:9>.withTag({type: "corypha"}),
        <primal:egg_boiled>,
        <primal:egg_death>,
        <primal:emerald_axe>,
        <primal:emerald_hatchet>,
        <primal:emerald_hoe>,
        <primal:emerald_knapp>,
        <primal:emerald_pickaxe>,
        <primal:emerald_point>,
        <primal:emerald_saw>,
        <primal:emerald_shovel>,
        <primal:emerald_workblade>,
        <primal:eroded_end_stone>,
        <primal:eroded_end_stone:1>,
        <primal:eroded_end_stone:2>,
        <primal:eroded_end_stone:3>,
        <primal:eroded_end_stone:4>,
        <primal:eroded_end_stone:5>,
        <primal:eroded_end_stone:6>,
        <primal:eroded_end_stone:7>,
        <primal:fence>,
        <primal:fence:1>,
        <primal:fence:2>,
        <primal:fence:3>,
        <primal:fermented_jungle>,
        <primal:ferro_slack>,
        <primal:ferro_stone>,
        <primal:ferro_stone:1>,
        <primal:ferro_stone:2>,
        <primal:ferro_stone:3>,
        <primal:ferro_stone:4>,
        <primal:ferro_stone:5>,
        <primal:ferro_stone:6>,
        <primal:ferro_stone:7>,
        <primal:fire_bow>,
        <primal:firepit>,
        <primal:fish_clown_cooked>,
        <primal:fish_clown_cured>,
        <primal:fish_clown_dried>,
        <primal:fish_clown_rotten>,
        <primal:fish_clown_salted>,
        <primal:fish_cod_cured>,
        <primal:fish_cod_dried>,
        <primal:fish_cod_rotten>,
        <primal:fish_cod_salted>,
        <primal:fish_lava_crawdad_cured>,
        <primal:fish_lava_crawdad_dried>,
        <primal:fish_lava_crawdad_raw>,
        <primal:fish_lava_crawdad_rotten>,
        <primal:fish_lava_crawdad_salted>,
        <primal:fish_lava_worm_cured>,
        <primal:fish_lava_worm_dried>,
        <primal:fish_lava_worm_raw>,
        <primal:fish_lava_worm_rotten>,
        <primal:fish_lava_worm_salted>,
        <primal:fish_puffer_cooked>,
        <primal:fish_puffer_cured>,
        <primal:fish_puffer_dried>,
        <primal:fish_puffer_rotten>,
        <primal:fish_puffer_salted>,
        <primal:fish_salmon_cured>,
        <primal:fish_salmon_dried>,
        <primal:fish_salmon_rotten>,
        <primal:fish_salmon_salted>,
        <primal:fish_trap>.withTag({type: "oak"}),
        <primal:fish_trap:1>.withTag({type: "spruce"}),
        <primal:fish_trap:2>.withTag({type: "birch"}),
        <primal:fish_trap:3>.withTag({type: "jungle"}),
        <primal:fish_trap:4>.withTag({type: "acacia"}),
        <primal:fish_trap:5>.withTag({type: "dark_oak"}),
        <primal:fish_trap:6>.withTag({type: "ironwood"}),
        <primal:fish_trap:7>.withTag({type: "yew"}),
        <primal:fish_trap:8>.withTag({type: "lacquer"}),
        <primal:fish_trap:9>.withTag({type: "corypha"}),
        <primal:fishing_rod_corypha>,
        <primal:fletching>,
        <primal:flint_axe>,
        <primal:flint_hatchet>,
        <primal:flint_hoe>,
        <primal:flint_knapp>,
        <primal:flint_pickaxe>,
        <primal:flint_point>,
        <primal:flint_saw>,
        <primal:flint_shears>,
        <primal:flint_shovel>,
        <primal:flint_workblade>,
        <primal:gate_corypha>,
        <primal:gate_ironwood>,
        <primal:gate_lacquer>,
        <primal:gate_yew>,
        <primal:gator_meat_cooked>,
        <primal:gator_meat_cured>,
        <primal:gator_meat_raw>,
        <primal:gator_meat_rotten>,
        <primal:gator_meat_salted>,
        <primal:glass_stick>,
        <primal:gold_dust>,
        <primal:gold_plate>,
        <primal:golden_stick>,
        <primal:grate_acacia>,
        <primal:grate_bigoak>,
        <primal:grate_birch>,
        <primal:grate_corypha>,
        <primal:grate_ironwood>,
        <primal:grate_jungle>,
        <primal:grate_lacquer>,
        <primal:grate_oak>,
        <primal:grate_spruce>,
        <primal:grate_thatch>,
        <primal:grated_gravel>,
        <primal:hardened_stone>,
        <primal:hardened_stone:1>,
        <primal:hardened_stone:2>,
        <primal:hardened_stone:3>,
        <primal:hardened_stone:4>,
        <primal:hardened_stone:5>,
        <primal:hardened_stone:6>,
        <primal:hardened_stone:7>,
        <primal:hardened_stone:8>,
        <primal:hardened_stone:9>,
        <primal:hardened_stone:10>,
        <primal:hardened_stone:11>,
        <primal:hardened_stone:12>,
        <primal:hardened_stone:13>,
        <primal:hardened_stone:14>,
        <primal:hardened_stone:15>,
        <primal:hibachi>.withTag({type: "mud"}),
        <primal:hibachi:1>.withTag({type: "terra"}),
        <primal:hibachi:2>.withTag({type: "cinis"}),
        <primal:hibachi:3>.withTag({type: "adobe"}),
        <primal:hide_dried>,
        <primal:hide_raw>,
        <primal:hide_salted>,
        <primal:hide_spoiled>,
        <primal:hide_tanned>,
        <primal:horse_meat_cooked>,
        <primal:horse_meat_cured>,
        <primal:horse_meat_dried>,
        <primal:horse_meat_raw>,
        <primal:horse_meat_rotten>,
        <primal:horse_meat_salted>,
        <primal:ignis_fatuus>,
        <primal:inferum_ground>,
        <primal:iron_bloom>,
        <primal:iron_clippers>,
        <primal:iron_dust>,
        <primal:iron_gallagher>,
        <primal:iron_mesh>,
        <primal:iron_pin>,
        <primal:iron_plate>,
        <primal:iron_ring>,
        <primal:iron_saw>,
        <primal:iron_strand>,
        <primal:iron_workblade>,
        <primal:ironglass>,
        <primal:ironwood_bow>,
        <primal:ironwood_stick>,
        <primal:jackolantern>,
        <primal:kiln_adobe>,
        <primal:kiln_air>,
        <primal:lacquer_stick>,
        <primal:ladder_acacia>,
        <primal:ladder_bigoak>,
        <primal:ladder_birch>,
        <primal:ladder_block_andesite>,
        <primal:ladder_block_cobblestone>,
        <primal:ladder_block_cobblestone_mossy>,
        <primal:ladder_block_diorite>,
        <primal:ladder_block_endbrick>,
        <primal:ladder_block_endstone>,
        <primal:ladder_block_granite>,
        <primal:ladder_block_netherbrick>,
        <primal:ladder_block_netherrack>,
        <primal:ladder_block_netherstone>,
        <primal:ladder_block_smoothandesite>,
        <primal:ladder_block_smoothdiorite>,
        <primal:ladder_block_smoothgranite>,
        <primal:ladder_block_smoothstone>,
        <primal:ladder_block_stonebrick>,
        <primal:ladder_block_stonebrick_cracked>,
        <primal:ladder_block_stonebrick_mossy>,
        <primal:ladder_corypha>,
        <primal:ladder_ironwood>,
        <primal:ladder_jungle>,
        <primal:ladder_lacquer>,
        <primal:ladder_oak>,
        <primal:ladder_spruce>,
        <primal:ladder_yew>,
        <primal:lantern_empty>,
        <primal:lantern_ignis>,
        <primal:lantern_nether>,
        <primal:lantern_redstone>,
        <primal:lantern_torch>,
        <primal:lead_dust>,
        <primal:lead_ingot>,
        <primal:lead_nugget>,
        <primal:lead_plate>,
        <primal:leather_boiled>,
        <primal:leather_cordage>,
        <primal:leather_strip>,
        <primal:leaves>,
        <primal:leaves:1>,
        <primal:lever_nether>,
        <primal:llama_meat_charqui>,
        <primal:llama_meat_cooked>,
        <primal:llama_meat_raw>,
        <primal:llama_meat_rotten>,
        <primal:llama_meat_salted>,
        <primal:loam_block>,
        <primal:logs>,
        <primal:logs:1>,
        <primal:logs_split_acacia>,
        <primal:logs_split_bigoak>,
        <primal:logs_split_birch>,
        <primal:logs_split_corypha>,
        <primal:logs_split_ironwood>,
        <primal:logs_split_jungle>,
        <primal:logs_split_oak>,
        <primal:logs_split_spruce>,
        <primal:logs_split_yew>,
        <primal:logs_stacked>,
        <primal:logs_stacked:1>,
        <primal:logs_stacked:2>,
        <primal:logs_stacked:3>,
        <primal:logs_stacked:4>,
        <primal:logs_stacked:5>,
        <primal:logs_stacked:6>,
        <primal:logs_stacked:7>,
        <primal:logs_stacked_corypha>,
        <primal:logs_stripped>,
        <primal:logs_stripped:1>,
        <primal:logs_stripped:2>,
        <primal:logs_stripped:3>,
        <primal:logs_stripped:4>,
        <primal:logs_stripped:5>,
        <primal:logs_stripped:6>,
        <primal:logs_stripped:7>,
        <primal:magma_basaltic>,
        <primal:magnetite_dust>,
        <primal:metalblock>,
        <primal:metalblock:1>,
        <primal:metalblock:2>,
        <primal:metalblock:3>,
        <primal:metalblock:4>,
        <primal:metalblock:5>,
        <primal:metalblock:6>,
        <primal:metalblock:7>,
        <primal:metalblock:8>,
        <primal:metalblock:9>,
        <primal:metalblock:10>,
        <primal:metalblock:11>,
        <primal:metalblock:12>,
        <primal:metalblock:13>,
        <primal:metalblock:14>,
        <primal:metalblock:15>,
        <primal:mold_spore>,
        <primal:mortar>,
        <primal:muck>,
        <primal:muck_molten>,
        <primal:mud_brick_dry>,
        <primal:mud_brick_wet>,
        <primal:mud_clump>,
        <primal:mud_dried>,
        <primal:mud_dried:1>,
        <primal:mud_dried:2>,
        <primal:mud_dried:3>,
        <primal:mud_dried:4>,
        <primal:mud_dried:5>,
        <primal:mud_dried:6>,
        <primal:mud_dried:7>,
        <primal:mud_wet>,
        <primal:mushroom_cooked>,
        <primal:nether_bush>,
        <primal:nether_cloth>,
        <primal:nether_cordage>,
        <primal:nether_earth>,
        <primal:nether_earth:1>,
        <primal:nether_earth:2>,
        <primal:nether_earth:3>,
        <primal:nether_earth:4>,
        <primal:nether_earth:5>,
        <primal:nether_earth:6>,
        <primal:nether_earth:7>,
        <primal:nether_farmland>,
        <primal:nether_fiber>,
        <primal:nether_fiber_pulp>,
        <primal:nether_gallagher>,
        <primal:nether_growth>,
        <primal:nether_mycelium>,
        <primal:nether_papyrus>,
        <primal:nether_path>,
        <primal:nether_root>,
        <primal:nether_seed>,
        <primal:nether_stone>,
        <primal:nether_stone:1>,
        <primal:nether_stone:2>,
        <primal:nether_stone:3>,
        <primal:nether_stone:4>,
        <primal:nether_stone:5>,
        <primal:nether_stone:6>,
        <primal:nether_stone:7>,
        <primal:nether_tinder>,
        <primal:nether_vine>,
        <primal:nether_wart_cooked>,
        <primal:nickel_dust>,
        <primal:nickel_ingot>,
        <primal:nickel_nugget>,
        <primal:nickel_plate>,
        <primal:night_stone>,
        <primal:night_stone:1>,
        <primal:night_stone:2>,
        <primal:night_stone:3>,
        <primal:night_stone:4>,
        <primal:night_stone:5>,
        <primal:night_stone:6>,
        <primal:night_stone:7>,
        <primal:obsidian_axe>,
        <primal:obsidian_hatchet>,
        <primal:obsidian_hoe>,
        <primal:obsidian_knapp>,
        <primal:obsidian_lens>,
        <primal:obsidian_pickaxe>,
        <primal:obsidian_plate>,
        <primal:obsidian_point>,
        <primal:obsidian_saw>,
        <primal:obsidian_shard>,
        <primal:obsidian_shovel>,
        <primal:obsidian_transparent>,
        <primal:obsidian_transparent:1>,
        <primal:obsidian_transparent:2>,
        <primal:obsidian_workblade>,
        <primal:old_mans_beard>,
        <primal:opal>,
        <primal:opal_axe>,
        <primal:opal_hatchet>,
        <primal:opal_hoe>,
        <primal:opal_knapp>,
        <primal:opal_pickaxe>,
        <primal:opal_point>,
        <primal:opal_shovel>,
        <primal:opal_workblade>,
        <primal:ore_bog_iron>,
        <primal:ore_bog_iron:1>,
        <primal:ore_bog_iron:2>,
        <primal:ore_cluster_bog_iron>,
        <primal:ore_cluster_magnetite>,
        <primal:ore_cluster_zinc>,
        <primal:ore_iron>,
        <primal:ore_magnetite>,
        <primal:ore_magnetite:1>,
        <primal:ore_magnetite:2>,
        <primal:ore_opal>,
        <primal:ore_salt>,
        <primal:ore_salt:1>,
        <primal:ore_salt:2>,
        <primal:ore_zinc>,
        <primal:ore_zinc:1>,
        <primal:ore_zinc:2>,
        <primal:ortho_stone>,
        <primal:ortho_stone:1>,
        <primal:ortho_stone:2>,
        <primal:ortho_stone:3>,
        <primal:ortho_stone:4>,
        <primal:ortho_stone:5>,
        <primal:ortho_stone:6>,
        <primal:ortho_stone:7>,
        <primal:ovis_atre_milk>,
        <primal:ovis_atre_wool>,
        <primal:ovis_meat_cooked>,
        <primal:ovis_meat_cured>,
        <primal:ovis_meat_dried>,
        <primal:ovis_meat_raw>,
        <primal:ovis_meat_rotten>,
        <primal:ovis_meat_salted>,
        <primal:ovis_milk_bottle>,
        <primal:paraffin>,
        <primal:paraffin_clump>,
        <primal:pelt_animal>,
        <primal:pelt_animal_large>,
        <primal:pelt_bear_black>,
        <primal:pelt_bear_brown>,
        <primal:pelt_bear_polar>,
        <primal:pelt_cow>,
        <primal:pelt_deer>,
        <primal:pelt_dog>,
        <primal:pelt_donkey>,
        <primal:pelt_gator>,
        <primal:pelt_horse>,
        <primal:pelt_llama>,
        <primal:pelt_mooshroom>,
        <primal:pelt_mule>,
        <primal:pelt_ovis>,
        <primal:pelt_pig>,
        <primal:pelt_shark>,
        <primal:pelt_sheep>,
        <primal:pelt_wolf>,
        <primal:pigman_hide_dried>,
        <primal:pigman_hide_raw>,
        <primal:pigman_hide_salted>,
        <primal:pigman_hide_spoiled>,
        <primal:pigman_hide_tanned>,
        <primal:pigman_leather>,
        <primal:pigman_meat_cooked>,
        <primal:pigman_meat_cured>,
        <primal:pigman_meat_dried>,
        <primal:pigman_meat_raw>,
        <primal:pigman_meat_rotten>,
        <primal:pigman_meat_salted>,
        <primal:pitfall>,
        <primal:planks>,
        <primal:planks:1>,
        <primal:planks:2>,
        <primal:planks:3>,
        <primal:plant_cloth>,
        <primal:plant_cordage>,
        <primal:plant_fiber>,
        <primal:plant_fiber_pulp>,
        <primal:plant_papyrus>,
        <primal:plant_tinder>,
        <primal:platinum_dust>,
        <primal:platinum_ingot>,
        <primal:platinum_nugget>,
        <primal:platinum_plate>,
        <primal:porphyry_stone>,
        <primal:porphyry_stone:1>,
        <primal:porphyry_stone:2>,
        <primal:porphyry_stone:3>,
        <primal:porphyry_stone:4>,
        <primal:porphyry_stone:5>,
        <primal:porphyry_stone:6>,
        <primal:porphyry_stone:7>,
        <primal:potato_boiled>,
        <primal:potato_rotten>,
        <primal:pumpkin_piece>,
        <primal:purpurite_stone>,
        <primal:purpurite_stone:1>,
        <primal:purpurite_stone:2>,
        <primal:purpurite_stone:3>,
        <primal:purpurite_stone:4>,
        <primal:purpurite_stone:5>,
        <primal:purpurite_stone:6>,
        <primal:purpurite_stone:7>,
        <primal:quartz_axe>,
        <primal:quartz_clippers>,
        <primal:quartz_gallagher>,
        <primal:quartz_hatchet>,
        <primal:quartz_hoe>,
        <primal:quartz_knapp>,
        <primal:quartz_pickaxe>,
        <primal:quartz_point>,
        <primal:quartz_saw>,
        <primal:quartz_shears>,
        <primal:quartz_shovel>,
        <primal:quartz_vitrified>,
        <primal:quartz_vitrified_lens>,
        <primal:quartz_workblade>,
        <primal:quern>.withTag({type: "sarsen"}),
        <primal:quern:1>.withTag({type: "scoria"}),
        <primal:quern:2>.withTag({type: "purpurite"}),
        <primal:quern_buhrstone_carbonate>,
        <primal:redstone_sand>,
        <primal:rock_andesite>,
        <primal:rock_diorite>,
        <primal:rock_end>,
        <primal:rock_granite>,
        <primal:rock_netherrack>,
        <primal:rock_stone>,
        <primal:rot>,
        <primal:rush>,
        <primal:rush_seeds>,
        <primal:rush_seeds_cooked>,
        <primal:rush_stems>,
        <primal:salo>,
        <primal:salt_dust_fire>,
        <primal:salt_dust_netjry>,
        <primal:salt_dust_rock>,
        <primal:salt_dust_void>,
        <primal:salt_netjry_block>,
        <primal:sapling>,
        <primal:sapling:1>,
        <primal:sapling:2>,
        <primal:sarsen_stone>,
        <primal:sarsen_stone:1>,
        <primal:sarsen_stone:2>,
        <primal:sarsen_stone:3>,
        <primal:sarsen_stone:4>,
        <primal:sarsen_stone:5>,
        <primal:sarsen_stone:6>,
        <primal:sarsen_stone:7>,
        <primal:satetsu>,
        <primal:satetsu:1>,
        <primal:satetsu:2>,
        <primal:satetsu:3>,
        <primal:satetsu:4>,
        <primal:schist_blue_stone>,
        <primal:schist_blue_stone:1>,
        <primal:schist_blue_stone:2>,
        <primal:schist_blue_stone:3>,
        <primal:schist_blue_stone:4>,
        <primal:schist_blue_stone:5>,
        <primal:schist_blue_stone:6>,
        <primal:schist_blue_stone:7>,
        <primal:schist_green_stone>,
        <primal:schist_green_stone:1>,
        <primal:schist_green_stone:2>,
        <primal:schist_green_stone:3>,
        <primal:schist_green_stone:4>,
        <primal:schist_green_stone:5>,
        <primal:schist_green_stone:6>,
        <primal:schist_green_stone:7>,
        <primal:scoria_stone>,
        <primal:scoria_stone:1>,
        <primal:scoria_stone:2>,
        <primal:scoria_stone:3>,
        <primal:scoria_stone:4>,
        <primal:scoria_stone:5>,
        <primal:scoria_stone:6>,
        <primal:scoria_stone:7>,
        <primal:searing_ember>,
        <primal:searing_sprig>,
        <primal:shark_fin>,
        <primal:shark_meat_cooked>,
        <primal:shark_meat_cured>,
        <primal:shark_meat_dried>,
        <primal:shark_meat_raw>,
        <primal:shark_meat_rotten>,
        <primal:shark_meat_salted>,
        <primal:shark_tooth>,
        <primal:sharp_bone>,
        <primal:shelf_half>.withTag({type: "oak"}),
        <primal:shelf_half:1>.withTag({type: "spruce"}),
        <primal:shelf_half:2>.withTag({type: "birch"}),
        <primal:shelf_half:3>.withTag({type: "jungle"}),
        <primal:shelf_half:4>.withTag({type: "acacia"}),
        <primal:shelf_half:5>.withTag({type: "dark_oak"}),
        <primal:shelf_half:6>.withTag({type: "ironwood"}),
        <primal:shelf_half:7>.withTag({type: "yew"}),
        <primal:shelf_half:8>.withTag({type: "lacquer"}),
        <primal:shelf_half:9>.withTag({type: "corypha"}),
        <primal:shibuichi_dust>,
        <primal:shibuichi_ingot>,
        <primal:shibuichi_nugget>,
        <primal:shibuichi_plate>,
        <primal:silk_cordage>,
        <primal:silk_cordage_coiled>,
        <primal:silver_dust>,
        <primal:silver_ingot>,
        <primal:silver_nugget>,
        <primal:silver_plate>,
        <primal:sinuous_cordage>,
        <primal:sinuous_resin>,
        <primal:sinuous_spore>,
        <primal:sinuous_weed>,
        <primal:slab_corypha>,
        <primal:slab_glass>,
        <primal:slab_ironwood>,
        <primal:slab_lacquer>,
        <primal:slab_mud>,
        <primal:slab_netherearth>,
        <primal:slab_netherrack>,
        <primal:slab_netherstone>,
        <primal:slab_soulglass>,
        <primal:slab_yew>,
        <primal:slag>,
        <primal:slat_acacia>,
        <primal:slat_bigoak>,
        <primal:slat_birch>,
        <primal:slat_corypha>,
        <primal:slat_iron>,
        <primal:slat_ironwood>,
        <primal:slat_jungle>,
        <primal:slat_lacquer>,
        <primal:slat_oak>,
        <primal:slat_spruce>,
        <primal:slat_yew>,
        <primal:smelter>.withTag({type: "mud"}),
        <primal:smelter:1>.withTag({type: "terra"}),
        <primal:smelter:2>.withTag({type: "cinis"}),
        <primal:smelter:3>.withTag({type: "adobe"}),
        <primal:smelter_lid_adobe>,
        <primal:smelter_lid_cinis>,
        <primal:smelter_lid_mud>,
        <primal:smelter_lid_terra>,
        <primal:smoke>,
        <primal:soul_residue>,
        <primal:soul_stone>,
        <primal:soul_stone:1>,
        <primal:soul_stone:2>,
        <primal:soul_stone:3>,
        <primal:soul_stone:4>,
        <primal:soul_stone:5>,
        <primal:soul_stone:6>,
        <primal:soul_stone:7>,
        <primal:soulglass>,
        <primal:stairs_carbonate_flag>,
        <primal:stairs_corypha>,
        <primal:stairs_dirt>,
        <primal:stairs_ferro_flag>,
        <primal:stairs_ironwood>,
        <primal:stairs_lacquer>,
        <primal:stairs_mud>,
        <primal:stairs_nether_earth>,
        <primal:stairs_nether_path>,
        <primal:stairs_nether_stone>,
        <primal:stairs_netherrack>,
        <primal:stairs_night_stone>,
        <primal:stairs_path>,
        <primal:stairs_sarsen>,
        <primal:stairs_scoria>,
        <primal:steel_ingot>,
        <primal:steel_nugget>,
        <primal:steel_plate>,
        <primal:stone_gallagher>,
        <primal:storage_crate>,
        <primal:storage_crate:1>,
        <primal:storage_crate:2>,
        <primal:storage_crate:3>,
        <primal:storage_crate:4>,
        <primal:storage_crate:5>,
        <primal:storage_crate:6>,
        <primal:storage_crate:7>,
        <primal:storage_crate:8>,
        <primal:storage_crate:9>,
        <primal:strangle_weed>,
        <primal:sword_crude_bone>,
        <primal:sword_crude_flint>,
        <primal:sword_crude_iron>,
        <primal:sword_crude_quartz>,
        <primal:sword_crude_wootz>,
        <primal:tall_grass_growing>,
        <primal:tall_grass_seeds>,
        <primal:tallow>,
        <primal:tamahagane_bloom>,
        <primal:tamahagane_dust>,
        <primal:tamahagane_ingot>,
        <primal:tamahagane_nugget>,
        <primal:tamahagane_plate>,
        <primal:tannin>,
        <primal:tannin_bottle>,
        <primal:tannin_ground>,
        <primal:tatami_bed>.withTag({type: "oak"}),
        <primal:tatami_bed:1>.withTag({type: "spruce"}),
        <primal:tatami_bed:2>.withTag({type: "birch"}),
        <primal:tatami_bed:3>.withTag({type: "jungle"}),
        <primal:tatami_bed:4>.withTag({type: "acacia"}),
        <primal:tatami_bed:5>.withTag({type: "dark_oak"}),
        <primal:tatami_bed:6>.withTag({type: "ironwood"}),
        <primal:tatami_bed:7>.withTag({type: "yew"}),
        <primal:tatami_bed:8>.withTag({type: "lacquer"}),
        <primal:tatami_bed:9>.withTag({type: "corypha"}),
        <primal:terra_block>,
        <primal:terra_brick_dry>,
        <primal:terra_brick_wet>,
        <primal:terra_clump>,
        <primal:terracotta_block>,
        <primal:terracotta_block:1>,
        <primal:terracotta_block:2>,
        <primal:terracotta_block:3>,
        <primal:terracotta_block:4>,
        <primal:terracotta_block:5>,
        <primal:terracotta_block:6>,
        <primal:terracotta_block:7>,
        <primal:thatch>,
        <primal:thatch_nether>,
        <primal:thatch_wet>,
        <primal:thatching_dry>,
        <primal:thatching_nether>,
        <primal:thatching_wet>,
        <primal:thin_slab_acacia>,
        <primal:thin_slab_bigoak>,
        <primal:thin_slab_birch>,
        <primal:thin_slab_corypha>,
        <primal:thin_slab_glass>,
        <primal:thin_slab_ironwood>,
        <primal:thin_slab_jungle>,
        <primal:thin_slab_lacquer>,
        <primal:thin_slab_oak>,
        <primal:thin_slab_soulglass>,
        <primal:thin_slab_spruce>,
        <primal:thin_slab_thatch>,
        <primal:thin_slab_yew>,
        <primal:tin_dust>,
        <primal:tin_ingot>,
        <primal:tin_nugget>,
        <primal:tin_plate>,
        <primal:torch_nether>,
        <primal:torch_nether_lit>,
        <primal:torch_wood>,
        <primal:urushi>,
        <primal:urushi_bottle>,
        <primal:urushi_ground>,
        <primal:valus_bread>,
        <primal:valus_fiber>,
        <primal:valus_melon>,
        <primal:valus_omniferum>,
        <primal:valus_seed>,
        <primal:valus_sepals>,
        <primal:valus_stalk_fresh>,
        <primal:valus_stalk_withered>,
        <primal:vanadium_dust>,
        <primal:vanadium_ingot>,
        <primal:vanadium_nugget>,
        <primal:vanadium_plate>,
        <primal:void_cordage>,
        <primal:void_fiber>,
        <primal:void_grass>,
        <primal:void_grass_root>,
        <primal:void_seed>,
        <primal:wall>,
        <primal:wall:1>,
        <primal:wall:2>,
        <primal:wall:3>,
        <primal:wall:4>,
        <primal:wall:5>,
        <primal:wall:6>,
        <primal:wall:7>,
        <primal:wall:8>,
        <primal:wall:9>,
        <primal:wall:10>,
        <primal:wall:11>,
        <primal:wall:12>,
        <primal:wall:14>,
        <primal:wall:14>,
        <primal:wall:15>,
        <primal:waste>,
        <primal:wax_residue>,
        <primal:wheat_ground>,
        <primal:wolf_head_item>,
        <primal:wolf_meat_cooked>,
        <primal:wolf_meat_cured>,
        <primal:wolf_meat_dried>,
        <primal:wolf_meat_raw>,
        <primal:wolf_meat_rotten>,
        <primal:wolf_meat_salted>,
        <primal:wood_pin>,
        <primal:wootz_dust>,
        <primal:wootz_ingot>,
        <primal:wootz_nugget>,
        <primal:wootz_plate>,
        <primal:worktable_shelf>.withTag({type: "oak"}),
        <primal:worktable_shelf:1>.withTag({type: "spruce"}),
        <primal:worktable_shelf:2>.withTag({type: "birch"}),
        <primal:worktable_shelf:3>.withTag({type: "jungle"}),
        <primal:worktable_shelf:4>.withTag({type: "acacia"}),
        <primal:worktable_shelf:5>.withTag({type: "dark_oak"}),
        <primal:worktable_shelf:6>.withTag({type: "ironwood"}),
        <primal:worktable_shelf:7>.withTag({type: "yew"}),
        <primal:worktable_shelf:8>.withTag({type: "lacquer"}),
        <primal:worktable_shelf:9>.withTag({type: "corypha"}),
        <primal:worktable_slab>.withTag({type: "oak"}),
        <primal:worktable_slab:1>.withTag({type: "spruce"}),
        <primal:worktable_slab:2>.withTag({type: "birch"}),
        <primal:worktable_slab:3>.withTag({type: "jungle"}),
        <primal:worktable_slab:4>.withTag({type: "acacia"}),
        <primal:worktable_slab:5>.withTag({type: "dark_oak"}),
        <primal:worktable_slab:6>.withTag({type: "ironwood"}),
        <primal:worktable_slab:7>.withTag({type: "yew"}),
        <primal:worktable_slab:8>.withTag({type: "lacquer"}),
        <primal:worktable_slab:9>.withTag({type: "corypha"}),
        <primal:yew_aril>,
        <primal:yew_aril_seedless>,
        <primal:yew_bow>,
        <primal:yew_seed>,
        <primal:yew_stick>,
        <primal:zinc_dust>,
        <primal:zinc_ingot>,
        <primal:zinc_nugget>,
        <primal:zinc_plate>,
        <primal_tech:bone_axe>,
        <primal_tech:bone_club>,
        <primal_tech:bone_knife>,
        <primal_tech:bone_pickaxe>,
        <primal_tech:bone_shard>,
        <primal_tech:bone_shears>,
        <primal_tech:bone_shovel>,
        <primal_tech:bone_sword>,
        <primal_tech:charcoal_block>,
        <primal_tech:charcoal_hopper>,
        <primal_tech:clay_kiln>,
        <primal_tech:fibre_torch>,
        <primal_tech:fibre_torch_lit>,
        <primal_tech:fire_sticks>,
        <primal_tech:flint_block>,
        <primal_tech:flint_edged_disc>,
        <primal_tech:fluid_bladder>,
        <primal_tech:leaf_bed>,
        <primal_tech:plant_fibres>,
        <primal_tech:rock>,
        <primal_tech:stick_bundle>,
        <primal_tech:stone_anvil>,
        <primal_tech:stone_club>,
        <primal_tech:stone_grill>,
        <primal_tech:stone_mallet>,
        <primal_tech:twine>,
        <primal_tech:water_saw>,
        <primal_tech:wood_club>,
        <primal_tech:wooden_basin>,
        <primal_tech:wooden_hopper>,
        <primal_tech:work_stump>,
        <primal_tech:work_stump_upgraded>,
        <primalchests:primal_chest>
    ]



    /*

    "Minecraft" : [
        //All (sand)stones and slabs and stone bricks
            <minecraft:stone>,
            <minecraft:stone:*>,
            <minecraft:cobblestone>,
            <minecraft:sandstone>,
            <minecraft:sandstone:*>,
            <minecraft:stone_slab>,
            <minecraft:stone_slab:1>,
            <minecraft:stone_slab:3>,
            <minecraft:stone_slab:5>,
            <minecraft:mossy_cobblestone>,
            <minecraft:red_sandstone>,
            <minecraft:red_sandstone:*>,
            <minecraft:stonebrick>,
            <minecraft:stonebrick:1>,
            <minecraft:stonebrick:2>,
            <minecraft:stonebrick:3>,
        //Wood logs, planks, slabs etc
            <minecraft:planks>,
            <minecraft:planks:1>,
            <minecraft:planks:2>,
            <minecraft:planks:3>,
            <minecraft:planks:4>,
            <minecraft:planks:5>,
            <minecraft:log>,
            <minecraft:log:1>,
            <minecraft:log:2>,
            <minecraft:log:3>,
            <minecraft:wooden_slab>,
            <minecraft:wooden_slab:1>,
            <minecraft:wooden_slab:2>,
            <minecraft:wooden_slab:3>,
            <minecraft:wooden_slab:4>,
            <minecraft:wooden_slab:5>,
            <minecraft:log2>,
            <minecraft:log2:1>,
        //Clay bricks and brick block/slab
            <minecraft:stone_slab:4>,
            <minecraft:brick_block>,
            <minecraft:brick>,
        //Ice, snow
            <minecraft:snow>,
            <minecraft:snow_layer>,
            <minecraft:snowball>,
            <minecraft:ice>,
            <minecraft:packed_ice>,
        //Clay and ball
            <minecraft:clay>,
            <minecraft:clay_ball>,
        //Pumkins
            <minecraft:lit_pumpkin>,
            <minecraft:pumpkin>,
        //Melon 
            <minecraft:melon_block>,
            <minecraft:melon>,
            <minecraft:speckled_melon>,
        //Mycelium
            <minecraft:mycelium>,
        //Terracotta
            <minecraft:hardened_clay>,
            <minecraft:stained_hardened_clay>,
            <minecraft:stained_hardened_clay:*>,
        //Concrete
            <minecraft:concrete>,
            <minecraft:concrete:*>,
        //Haybale, boneblock, cobweb
            <minecraft:hay_block>,
            <minecraft:bone_block>,
            <minecraft:web>,
        //Leaves
            <minecraft:leaves>,
            <minecraft:leaves:1>,
            <minecraft:leaves:2>,
            <minecraft:leaves:3>,
            <minecraft:leaves2>,
            <minecraft:leaves2:1>,

        //Grass, flowers, shrooms, cactus, vines, lily pad
            <minecraft:tallgrass:*>,
            <minecraft:deadbush>,
            <minecraft:yellow_flower>,
            <minecraft:red_flower>,
            <minecraft:red_flower:*>,
            <minecraft:brown_mushroom>,
            <minecraft:red_mushroom>,
            <minecraft:cactus>,
            <minecraft:vine>,
            <minecraft:waterlily>,
            <minecraft:double_plant:*>,
        //Torch and skulls
            <minecraft:torch>,
            <minecraft:skull>,
            <minecraft:skull:*>
    
        
    ]
  
    */




    /*
    "Rafts" : [
        <jarm:jungle_raft>,
        <jarm:acacia_raft>,
        <jarm:dark_oak_raft>
    ]
    */
};

static liquids as ILiquidStack [] = [
    //MC liquids
        <liquid:water>,
        <liquid:lava>
    
];

static ores as IItemStack [][string] = {

};